### ISSUE TITLE
What does set() do?

### ISSUE THREAD

**Issue by ryanking1809** [alloc/ople#12]
What does `set()` do? (Apologies for all the questions, please take your time to respond)

ie. Why should I be doing this?

```js
  constructor(props) {
    super()
    initOple(this, (self, set, emit) => {
      set(props)
    })
  }
```
```js
const Todo = createClass(
  'Todo',
  props => (todo, set, emit) => {
    set(props)
  }
)
```

instead of this?

```js
  constructor(props) {
    super()
    Object.keys(props).forEach(p => this[p] = props[p])
    initOple(this, (self, set, emit) => {
      // ...
    })
  }
```
```js
const Todo = createClass(
  'Todo',
  props => (todo, set, emit) => {
    ...props
  }
)
```

**Comment by aleclarson** [comment]
No problem, keep 'em coming!

First off, the `set` function is a **bound** instance of the `Ople#set` method.

```js
constructor(props) {
  super()

  // These two lines have the same effect.
  this.set(props)
  initOple(this, (_, set) => set(props))
}
```

#### Why use the `set` function instead of `this.set`?

Only if you care about code minification. The `set` identifier can be minified into a single character, while `this.set` can't be minified at all (without trickery). It's not the end of the world if you use `this.set` everywhere.

#### Why use `set(props)` and not `Object.assign(this, props)`?

The `set` function has support for `get` properties, which are transformed into observable derivations under-the-hood. 

```js
createClass('Foo', props => (self, set) => {
  set({
    values: o([]),
    get sum() {
      // This only runs when `self.values` is mutated.
      // Observers are only notified when the result is different.
      return self.values.reduce((sum, n) => sum + n, 0)
    },
  })
})
```

Additionally, function values are wrapped with `no` (to disable observation) and `withOple` (to set the Ople context automatically). An exception this rule: Properties named `^get[A-Z]` (eg: `getFoo` or `getBar`) are never wrapped.

**Comment by ryanking1809** [comment]
Got it - So it's really just a helper to ensure observables are initiated within the ople context, and if I really wanted to set up my own observable getters, etc, I could just do `Object.assign(this, observableProps)` within the Ople context?

**Comment by aleclarson** [comment]
To setup your own observable getter, you would do something like this:

```js
const get = o(() => this.a + this.b)
Object.defineProperty(this, 'c', { get })
setEffect(get, active => {
  if (active) {} // TODO: do something here to work with `useOple`
  else get.dispose()
})
```

..which could even be wrapped in a mixin, if you wanted.

Btw, you can use `get` properties with `this.set` if that works better for you:

```js
constructor() {
  super()

  this.set({
    get sum() { ... }
  })
}
```

I'll try to get https://github.com/alloc/ople/issues/6#issuecomment-649153844 added soon, since that's the best solution for `Ople` subclasses. You could open a PR if you want it faster or if you just want to help. ;)

**Comment by ryanking1809** [comment]
I'm still wrapping my head around the source to be honest, but I will have a crack at a PR if things start to crystalize before you get around to it :)
