### ISSUE TITLE
Fire function on dispose

### ISSUE THREAD

**Issue by ryanking1809** [alloc/ople#7]
It would be great to be able to fire an event or function when an Ople object is disposed. Is this possible?

**Comment by aleclarson** [comment]
This mixin should do the trick:

```js
import {setEffect} from 'ople'

function onDispose(effect) {
  setEffect(effect, active => {
    if (!active) effect()
  })
}
```

You can use it like this:

```js
// inside an Ople context
onDispose(() => {
  console.log('disposed')
})
```

In the future, maybe I'll give all Ople objects a `dispose` event.

**Comment by ryanking1809** [comment]
Ah ok, so `active` will be false on disposal? And `setEffect` fires whenever a change happens?

**Comment by aleclarson** [comment]
> so `active` will be false on disposal?

Yup.

> And `setEffect` fires whenever a change happens?

I assume you mean the `setEffect` callback? Either way, no.

The `setEffect` callback's job is to either create a disposable (eg: an event listener) when `active == true` or dispose of it when `active == false`.

&nbsp;

### Why `setEffect` is weird

Let me start by saying these details are irrelevant if you're not using `useOple` anywhere, but it will give you some insight on why `setEffect` is the way it is.

The reason `setEffect` takes an `(active: boolean) => void` callback (instead of a simpler dispose callback) is due to a workaround that allows Ople objects to be created while a React component is rendering (eg: by calling `useOple`) without leaking memory if React decides to "throw away" the rendered element instead of mounting it.

To avoid leaking memory, Ople objects returned by `useOple` must dispose themselves immediately and, once the component is mounted, any effects are restored gracefully. 

So when `setEffect` is called, it's called immediately with `active == true` (unless the Ople context is disposed). Once the Ople context's initializer is finished, the `setEffect` callback is called with `active == false` (but again, only if `useOple` is used). 

Once the component is mounted, the `setEffect` callback is called with `active == true` again. And finally, when the component unmounts, the callback is passed `active == false` for a final time.

Hope that clears things up 🙈

**Comment by ryanking1809** [comment]
I haven't got around to useOple yet, but makes sense, thanks!
